### ISSUE TITLE
TFS 2015 update 2 troubles

### ISSUE THREAD

**Issue by Wylde44** [tfsaggregator/tfsaggregator#122] opened 2016-04-05 13:02 UTC
Hi, guys.
I have an issue due to TFS update. Aggregator fails with an exception:

> The description for Event ID 47513 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> Exception encountered processing notification: Object reference not set to an instance of an object. 
> Stack Trace:   at Aggregator.Core.Facade.FieldCollectionWrapper.ApplyDoubleFix(Field field) in C:\projects\tfsaggregator\Aggregator.Core\Facade\FieldCollectionWrapper.cs:line 63
>    at RESERVED.Script_RequirementsAutomation.RunScript(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger) in c:\Users\tfs13service\AppData\Local\Temp\0rlmvh3k.0.cs:line 21
>    at Aggregator.Core.Script.DotNetScriptEngine`1.RunScript(Assembly assembly, String scriptName, IWorkItem self, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 149
>    at Aggregator.Core.Script.DotNetScriptEngine`1.Run(String scriptName, IWorkItem workItem, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 212
>    at Aggregator.Core.EventProcessor.ApplyRule(Rule rule, IWorkItem workItem) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 109
>    at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`1 rules) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 95
>    at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 62
>    at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84
> 
> the message resource is present but the message is not found in the string/message table

TFS 2015 update 2
Aggregator 2.1.169

Thanks in advance!

**Comment by giuliov** [comment] 2016-04-05 13:54
If you updated TFS, must uninstall and reinstall Aggregator

----- Messaggio originale -----
Da: "Wylde44" <notifications@github.com>
Inviato: ‎05/‎04/‎2016 15:02
A: "tfsaggregator/tfsaggregator" <tfsaggregator@noreply.github.com>
Oggetto: [tfsaggregator/tfsaggregator] TFS 2015 update 2 troubles (#122)

Hi, guys.
I have an issue due to TFS update. Aggregator fails with an exception:
The description for Event ID 47513 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
If the event originated on another computer, the display information had to be saved with the event.
The following information was included with the event: 
Exception encountered processing notification: Object reference not set to an instance of an object. 
Stack Trace: at Aggregator.Core.Facade.FieldCollectionWrapper.ApplyDoubleFix(Field field) in C:\projects\tfsaggregator\Aggregator.Core\Facade\FieldCollectionWrapper.cs:line 63
at RESERVED.Script_RequirementsAutomation.RunScript(IWorkItemExposed self, IWorkItemRepositoryExposed store, IRuleLogger logger) in c:\Users\tfs13service\AppData\Local\Temp\0rlmvh3k.0.cs:line 21
at Aggregator.Core.Script.DotNetScriptEngine1.RunScript(Assembly assembly, String scriptName, IWorkItem self, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 149
at Aggregator.Core.Script.DotNetScriptEngine1.Run(String scriptName, IWorkItem workItem, IWorkItemRepository store) in C:\projects\tfsaggregator\Aggregator.Core\Script\DotNetScriptEngine{TCodeDomProvider}.cs:line 212
at Aggregator.Core.EventProcessor.ApplyRule(Rule rule, IWorkItem workItem) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 109
at Aggregator.Core.EventProcessor.ApplyRules(IWorkItem workItem, IEnumerable`1 rules) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 95
at Aggregator.Core.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 62
at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84
the message resource is present but the message is not found in the string/message table
TFS 2015 update 2
Aggregator 2.1.169
Thanks in advance!

**Comment by jessehouwing** [comment] 2016-04-05 14:03
It looks like the aggregator is running... Can you share the rule in question?

**Comment by Wylde44** [comment] 2016-04-05 14:17
I reinstalled it, it doesn't work with my previous policies-file. But it began to work with simple rules like creating new items. It looks like i have to review my policies...Thanks.

**Comment by jessehouwing** [comment] 2016-04-05 14:18
It seems that this call is causing issues:

https://github.com/tfsaggregator/tfsaggregator/blob/release/2.1.0-rc1/Aggregator.Core/Facade/FieldCollectionWrapper.cs#L63

Which seems to indicate that this.context is actually null. It would be really helpful if @Wylde44 could confirm this in the debugger.

We've done quite a bit of refactoring of the RequestContext, so it's possible this got messed up somehow.

**Comment by jessehouwing** [comment] 2016-04-05 14:21
I've been looking through the code, any chance you're using the Revisions, LastRevision, PreviousRevision or NextRevision?

**Comment by jessehouwing** [comment] 2016-04-05 14:24
Pushing a change that will ensure that Revision will always have a context object. That might be the cause.

**Comment by Wylde44** [comment] 2016-04-05 14:26
Yeah, I use last revision to catch the field change.

**Comment by jessehouwing** [comment] 2016-04-05 14:29
Can you try this build once it finishes?
https://ci.appveyor.com/project/giuliov/tfsaggregator/build/2.1.173-release/2.1.0-rc1

**Comment by jessehouwing** [comment] 2016-04-05 15:10
Also note the change with this update where LastRevision may need to be replaced with PreviousRevision etc..

**Comment by Wylde44** [comment] 2016-04-06 07:09
TFSAggregator-2.1.173-Release does not seem to be working at all both with default and my policies. There are no events from aggregator in the Event Viewer.

**Comment by Wylde44** [comment] 2016-04-06 07:31
Debug version also has no results.

**Comment by jessehouwing** [comment] 2016-04-06 08:23
I just tested the following rule, it works. It'd be really helpful if you;d be able to share the rule. even if it's in private to either one of us.

Can you verify the binaries are present here:
```
C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin\Plugins
```

My sample policy is attached:
[TFSAggregator2.ServerPlugin.policies.txt](https://github.com/tfsaggregator/tfsaggregator/files/205996/TFSAggregator2.ServerPlugin.policies.txt)

**Comment by jessehouwing** [comment] 2016-04-06 08:25
You could also try disabling the `debug="true"` flag on your policy, we've introduced a number of additional checks and logging statements that trigger on "complex" fields which are only enabled when the above flag is turned on.

**Comment by Wylde44** [comment] 2016-04-06 09:04
Sorry, I misinformed you. It works, but for now i can see debug messages in Debug View, which did't work for me earlier and it stopped write messages to Event Viewer. Now i am to check all the rules, i will let you know the results a little bit later.

**Comment by Wylde44** [comment] 2016-04-06 14:21
it looks like everything is fine. Most rules work, but the process requires more time to check it. Thank you so much for the urgent fixes! By the way i tried not to replace LastRevision and it works as suggested.

**Comment by jessehouwing** [comment] 2016-04-06 15:23
In that case let us close this issue. Don't hesitate to file additional issues as your tests progress. We want to make sure this thing is stable and behaves as expected. If you're able to give us sample rules which we can put into our tests, that's helpful.

**Closed by jessehouwing** 2016-04-06 15:23 UTC
