### ISSUE TITLE
Sum rule does not work when parent field is empty.

### ISSUE THREAD

**Issue by ASolovyev** [tfsaggregator/tfsaggregator#63] opened 2015-10-01 13:42 UTC
Rule

    <rule name="Original_Estimate_Calc"
    appliesTo="*">
     <![CDATA[
     if (self.HasParent())
     {
    self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] = (double)self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] +(double)self["Microsoft.VSTS.Scheduling.OriginalEstimate"];
    }
     ]]>
    </rule> 

Dont work when (double)self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"]  is empty (WI have just been created)

**Comment by giuliov** [comment] 2015-10-01 14:43
Try this

```
if (self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"].Status == FieldStatus.Valid) {
  self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] = (double)self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] +(double)self["Microsoft.VSTS.Scheduling.OriginalEstimate"];
}
```
shorter form
```
var parentField = self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"];
if (parentField.Status == FieldStatus.Valid) {
  parentField.Value += (double)self["Microsoft.VSTS.Scheduling.OriginalEstimate"];
}
```

**Comment by jessehouwing** [comment] 2015-10-01 20:56
using  `((double)self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"]  ?? 0d)` probably works as well. The case to double will fail as the value will be `null` unless the field has a default value rule on it.

**Comment by ASolovyev** [comment] 2015-10-02 10:19
Well. As i see we cant even set a value to the field  with null value. Am i right? In that case i will just make a workitem rule to set estimate values to 0 when wit is creating.

**Comment by jessehouwing** [comment] 2015-10-02 14:26
I do not believe the issue is that you can't set the value. The issue is that the cast to double will fail. You could cast it to `double?` or do the null check before casting:

```
if (self.HasParent())
 {
self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] = ((double?)self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"]??0d) +((double?)self["Microsoft.VSTS.Scheduling.OriginalEstimate"]??0d);
}
```

or 

```
if (self.HasParent())
 {
self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"] = ((double)(self.Parent["Microsoft.VSTS.Scheduling.OriginalEstimate"]??0d)) +((double)(self["Microsoft.VSTS.Scheduling.OriginalEstimate"]??0d));
}
```

**Comment by ASolovyev** [comment] 2015-10-05 10:04
Yes. The issue that that if field have empty value - we can not set value in it.
I saw, that in that case we can make the aggregator do not work with this fields.
But in the case when i created, for example,  a User story with emty estimate fields and made a link to task - when i put a value into task's estimate fields it will not added to User story fields.

**Comment by jessehouwing** [comment] 2015-10-05 21:40
Have you tried the code above? have you looked at the Eventlog to see if a warning is being created?

**Comment by ASolovyev** [comment] 2015-10-06 08:58
yes, i tried. First Case ((double?)) works like a regular rule.  Second one is the same. :(
Eventlog is silent. It shows that rule is applyuing at child WI, and that is all. Logging level is diagnostic.
Maybe  i should debug it?

By the way, one more question if you dont mean:

When i changing remaining work or original estimate in child from 6 to 2 for example aggregator makes +2 in  parent WI and also adding all other estimate fields. What rule can help with this?

**Comment by giuliov** [comment] 2015-10-06 09:15
There was a bug regarding EventLog messages; it is fixed in the develop branch. Could be that you are using a version without that fix.
Please use the console app to validate your rules as suggested in the docs.

**Comment by ASolovyev** [comment] 2015-10-06 11:16
I am using 2.0.71 (2.0 Beta4)

**Comment by giuliov** [comment] 2015-10-09 06:23
Try using the latest code from develop branch. You will find updated docs and some fixes.

**Comment by jessehouwing** [comment] 2015-10-09 11:57
@giuliov,any specific change we can quickly cherry pick to master?

**Comment by giuliov** [comment] 2015-10-09 13:23
@jessehouwing bbf697f fix logging bug and 57405e7 for docs but not so sure of the result

**Comment by jessehouwing** [comment] 2015-10-10 19:35
Wrote a unit test specific for this case and updated the `RollUp.Policies` file:

```
        if (self.HasParent())
        {
            self.Parent["Total Work Remaining"] = (double)(self["Remaining Dev Work"]??0d) + (double)(self["Remaining Test Work"]??0d);
            self.Parent["Total Estimate"] = (double)(self["Estimated Dev Work"]??0d) + (double)(self["Estimated Test Work"]??0d);
            // Sum up all estimates to the sprint
            if ((System.DateTime)self["Finish Date"] > System.DateTime.Now) {
                // Log("Updating grand parent");
                self.Parent.Parent["Dev Estimate"] = self["Estimated Dev Work"]??0d;
                self.Parent.Parent["Test Estimate"] = self["Estimated Test Work"]??0d;
            }
        }
```

This syntax works for me in the test suite. If you can create a failing test from your code, it would help us debug this further.

**Comment by ASolovyev** [comment] 2015-10-12 10:00
Ok i will try this at week and post results here!

**Comment by jessehouwing** [comment] 2015-10-15 20:14
Do you have an update for us?

**Comment by ASolovyev** [comment] 2015-10-16 09:58
Yes!I have updates.
The case with ??0d works fine! Thank 
My bad was in wrong brackets placement.
((double)self.Parent["Original Estimate"]??0d) instead of (double)(self.Parent["Original Estimate"]??0d)

**Comment by giuliov** [comment] 2015-10-16 10:37
Great! Closing this and looking forward for your continued adoption.

**Closed by giuliov** 2015-10-16 10:37 UTC
Labels: help wanted, wontfix
