### ISSUE TITLE
Writing to History field causes infinite loop

### ISSUE THREAD

**Issue by jiri-matejka** [tfsaggregator/tfsaggregator#65] opened 2015-10-02 15:10 UTC
Hello,
writing anything to History causes that Aggregator's modification triggers a new Aggregator's modification.
TFS Express 2013 Update 4
Aggregator 2.0 beta 4 (https://github.com/tfsaggregator/tfsaggregator/releases/download/2.0.71/tfsaggregator-2.0.71-master-Release-2013.zip)

Add this single line to a rule			
	self.Fields["History"].Value = "Hello";

**Comment by jessehouwing** [comment] 2015-10-02 15:40
We can't really fix that, as the history field appends a new message.
You'll have to check yourself whether a comment needs to be added and
whether that's the only change. It's hard for us to judge whether you'd
want to update it or not.

**Comment by jiri-matejka** [comment] 2015-10-03 08:37
Ok, so when I change another field together with putting the comment to history, the infinite loop will not happen? In my case it happens anyway I think.

My use case is to extract working hours from work log in Description of a Task and sum them to Completed hours field. I used History for reporting non-parsable data.

In my opinion, if putting a comment to history is not supported by Aggregator, it should be not in API for the rule script, because it causes bad think to happen.

**Comment by giuliov** [comment] 2015-10-03 10:41
I just pushed on the develop branch an idea. @jiri-matejka you are right that History field is not easy to tame. My suggestion is to use a _marker_ to distinguish user changes from rules' changes.

    const string HistoryMarker = "===";
    
    int lastRevisionNo = self.Revisions.Count;
    Revision lastRevision = self.Revisions[ lastRevisionNo - 1 ];
    Field history = lastRevision.Fields["History"];
    string lastValue = (string) history.Value;
    
    logger.Log("At revision {0} History value is '{1}'", lastRevisionNo, lastValue);
    
    if (!lastValue.StartsWith(HistoryMarker))
    {
      self.History = HistoryMarker + "Hello";
      logger.Log("Marker added");
    }

The `Revisions` property requires the code in develop branch. I would like to have some feedback from you.

**Comment by jiri-matejka** [comment] 2015-10-03 15:50
Oh I finally understand your suggestion. You are just checking whether last revision is from the previous run of the rule and stopping the rule from further modifications in such case. In other words you already entered "infinite loop" but you can detect it and stop :) Yes, this is a solution for my problem (a dirty one, but only one I have). Thank you.

But I'm still wondering - why modification of Description is OK and adding a comment to History triggers infinite modifications of WI? I don't understand. Originally I expected this is simply a bug inside Aggregator.

**Comment by jessehouwing** [comment] 2015-10-03 19:56
**Some background information.** The TFS aggregator only updates a work item if any field has changed by its calculations. If the calculations yield the same value as last time, the work item is considered clean and no new revision is created.

The History field is a strange kind of field, it always being empty, unless you've added a new value to it while processing. Therefore, setting the history field to anything other than `string.Empty` or `null` will cause a workitem to be saved.

Whenever a workitem is saved, the TFS Aggregator triggers again. This is by design and allows for cascading rules. It's also why we've recently added a rate limiter. Normally the same set of rules triggers again, all calculations yield the same value and that breaks the loop that would otherwise be created.

*Except* when a rule always sets the value of the history field. As it was **empty** when we started calculating and is now **not empty** it will cause the work item to be saved.

To prevent this from happening there are a few things you can do:

 1. Before setting the History field, check the `.IsDirty` property of the work item. If it's not dirty, don't add anything to the history.
 2. Iterate through the revisions of the work item to ensure that you're not adding the same comment you added last time. This causes additional database and network traffic, and is therefore less desirable. (This requires an updated version of the Aggregator, as mentioned by @giuliov. This implementation may change before we merge to Master.
 3. Don't store your data in the History Field, instead stick it in a custom field or use an of the pre-existing fields to store your data in. (Don't append to an existing field as that would cause the same behavior)
 4. If you're not using Impersonation, check whether the "Changed By" field is set to the service account and assume that the changes are not made by a human, therefore skipping the changes to the history field.

I'm going to close this issue, as the behavior is per expectation and is how TFS has always dealt with the History field.

If you have a suggestion on how we should change the aggregator, then that would be a new issue describing the change.

Some things I can think of:

 * Generate a warning when saving and the only changed field is the History
 * Have a configurable list of fields to ignore when they're the only changed fields of a rule

So far I'm not convinced either is the correct way to handle this, I'd rather you'd use any of the above mentioned work-arounds.

I am going to add a page with Tips, Tricks and Pitfalls in the near future and will be sure to mention the dangers of the history field there.

**Closed by jessehouwing** 2015-10-03 19:56 UTC
