### ISSUE TITLE
Error "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by holcak** [tfsaggregator/tfsaggregator#32] opened 2015-05-15 11:21 UTC
Hello guys,

First, I thank you all for good work.
Second, I have a issue succesfully deploy tfsaggregator to the production TFS 2013 RTM server (no update installed). I have followed your instruction at "Installation" section. Thanks to DebugView I know, that plugin si working a do some job. But results are weird. 

1. when I use simple "Sum" aggregatorItem, result is always "0" in targetField regardless value in sourceField
2. when I use operation "CopyTo" like:

[AggregatorItem name="Update Priority" operation="CopyTo" operationType="Numeric" linkType="Children" linkLevel="1" workItemType="User Story" targetWorkItemType="Task"]
    [TargetField name="Priority"/]
    [SourceField name="Backlog Priority"/]
  [/AggregatorItem]

aggregator successfully recognize that conditions for parent aggregation are met, but then it fails with error:

TFSAggregator: Exception encountered processing Work Item [3483]: Object reference not set to an instance of an object. 
Stack Trace:   at TFSAggregator.Aggregator.IntegerAggregation(IEnumerable`1 sourceWorkItems, IWorkItem targetWorkItem, ConfigAggregatorItem configAggregatorItem) in d:\tfsaggregator-master\tfsaggregator-master\TFSAggregator\Aggregator.cs:line 88
   at TFSAggregator.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in d:\tfsaggregator-master\tfsaggregator-master\TFSAggregator\EventProcessor.cs:line 181

I built tfsaggregator solution with version of TFS libraries which are on production server at a moment. Changeset is the most recent, downloaded from main site. 

Any help is welcome.
Thanks.

Footnotes:
1. please delete project "https://github.com/Vaccano/TFS-Aggregator". I guess that this project is newer one (but its difficult to say), and that I am not the only one, who is confused by existence of second project.
2. Release version 0.1 from this site not function with TFS 2013 RTM (assembly mishmash, I guess its because some TFS update is required) and is pretty old. Cannot you roll out new release and maybe correct prerequisites please?

**Comment by holcak** [comment] 2015-05-15 11:25
hmm. do you know how I get the code to the text?.. nevermind, i changed a type of parenthesis

**Comment by giuliov** [comment] 2015-05-15 11:48
Regarding footnotes:
we will "retire" old sites, as soon as we release 2.0 (see develop branch). The change of version will clarify the confusion. Same goes for the releases.

**Comment by jessehouwing** [comment] 2015-05-15 11:58
The build requires TFS 2013 update 2 or better. Microsoft moved a number of classes and interfaces of the server object model to a different  namespace and assembly and forgot to create a binding policy to redirect the old ones to the new location. 

For us to be compatible with the latest update we need to use the current config. 

As I'm still using the current master version at a client, let me see what's going to with the null reference. Can you share the rules and the process template you're using?

**Comment by jessehouwing** [comment] 2015-05-15 12:01
For the sum issue, are all fields of the same type? There is an issue with summing up integer and assigning  to double or any mix of multiple numeric types in the same aggregate function. Sharing the exact rule will help. I suspect you're on the MSF Agile template... The 2013 rtm version?

**Comment by jessehouwing** [comment] 2015-05-15 12:25
Your copyTo has an incorrect rule, it has both the operationType and the Copy specified, it's currently going into the Integer operation, I guess it should read:

   operation<b>Type</b>="CopyTo" <s>operationType="Numeric" </s>

**Comment by holcak** [comment] 2015-05-15 12:44
2giuliov: thanks :)
2jessehouwing: 
1. do you mean the process template of TFS project collection? And all solution, or only file "ProcessTemplate.xml"? We can share it...
2. file "AggregatorItems.xml" (aka "rules" i guess):

```
<?xml version="1.0" encoding="utf-8"?>
<AggregatorItems tfsServerUrl="http://localhost/tfs/DynatechCollection" loggingVerbosity="Diagnostic" >

  <AggregatorItem name="Update Priority 2" operationType="CopyTo" linkType="Children" linkLevel="1" workItemType="User Story" targetWorkItemType="Task">
    <TargetField name="Priority"/>
    <SourceField name="Backlog Priority"/>
  </AggregatorItem>

  <AggregatorItem name="Test" operationType="Numeric" operation="Sum" linkType="Self" workItemType="Task">
    <TargetField name="Remaining Work"/>  
    <SourceField name="Original Estimate"/>
  </AggregatorItem>

</AggregatorItems>
```

3. yes, we started on MSF Agile template 2013 RTM, but we have modified it slightly after that. No big function changes...
4. mix of data types = no. both fields are "Double"

**Comment by holcak** [comment] 2015-05-15 12:46
good find (shame on me i guess ;). thanks for correction "CopyTo" rule.. now the error is different. 

TFSAggregator: Exception encountered processing Work Item [3483]: Value cannot be null.
Parametr name: format
Stack Trace:   at System.String.Format(String format, Object[] args)
   at TFSAggregator.Aggregator.CopyToAggregation(IWorkItem childWorkItem, IWorkItem parentWorkItem, ConfigAggregatorItem configAggregatorItem) in d:\tfsaggregator-master\tfsaggregator-master\TFSAggregator\Aggregator.cs:line 254
   at TFSAggregator.EventProcessor.ProcessEvent(IRequestContext requestContext, INotification notification) in d:\tfsaggregator-master\tfsaggregator-master\TFSAggregator\EventProcessor.cs:line 183

**Comment by holcak** [comment] 2015-05-15 12:50
correction: 
in "Test" rule both fields are the same type "Double"
in "Update Priority 2" rule field "Priority" is "Integer", "Backlog priority" is "Double"

**Comment by jessehouwing** [comment] 2015-05-15 12:57
Your CopyTo rule is missing it's "OutputFormat" parameter and the string format opertation balks on that. But I suspect it'll fail to save afterwards, as the value will be converted to string and there is no ConvertTo for the target workitem field type in there. That would be a small addition though.

**Comment by jessehouwing** [comment] 2015-05-15 13:01
I'd have to run a test for the Sum operation. It's something I've not been using personally and may have broken with the updates to handle null items in a single item.

**Comment by holcak** [comment] 2015-05-15 13:07
ah. I miss that the parametr "OutputFormat" is required. I tried your proposal and its works now. Thanks a lot :)

**Comment by jessehouwing** [comment] 2015-05-15 13:10
I echo what @giuliov says, when the new beta comes out, it's best to switch. The XML syntax is quite hard to understand and write correctly. I can only write it correctly by stepping through the code myself. It was not mine to begin with :).

The new syntax will support plain C# and should be a lot easier to use. We're going to be building in more type checks and have recently released an XSD for the config file format. Should make life *a lot* easier.

**Comment by jessehouwing** [comment] 2015-05-15 13:18
Pushed a new version that will at least default outputFormat to "{0}", that was simple to fix ;).

Did you grab those rules from anywhere? Are they incorrect in our documentation?

**Comment by holcak** [comment] 2015-05-15 13:25
Sounds good. We will look forward to it... thanks :)

Only info i have is from:
homepage https://github.com/tfsaggregator/tfsaggregator
and from
https://github.com/tfsaggregator/tfsaggregator/blob/master/readme.md

example of use it's defined in example "AggregatorItems.xml" file... Better documentation cannot hurt but for "public noncomercial solution" it's good enough I guess

**Comment by jessehouwing** [comment] 2015-05-15 13:27
I added a mention of TFS 2013 update 2 as minimum to build. I'm going to prepare a number of blogs to demonstrate the new version. The old one is having it's final few spasms before it will die a quick death ;).

**Comment by jessehouwing** [comment] 2015-05-15 13:44
Default Outputformat fixed in: https://github.com/tfsaggregator/tfsaggregator/commit/bf61c3fa26668c9c37fc7c8d5ad0074ab48b488a

**Comment by jessehouwing** [comment] 2015-05-15 13:55
Closing this issue based on your comment.

**Comment by holcak** [comment] 2015-05-15 14:01
please, just don't forget on issue with "Sum" operator... anything else from this ticket it's solved by now. thanks.

**Comment by jessehouwing** [comment] 2015-05-15 14:03
Please check this https://github.com/tfsaggregator/tfsaggregator/issues/32#issuecomment-102391890 to see if it causes the issue.

**Comment by holcak** [comment] 2015-05-15 14:08
Unfortunatelly no. The result is the same even if I use two sourceField parameters with same data type.

**Comment by jessehouwing** [comment] 2015-05-15 14:24
That's strange, we're extensively using the Sum operation in our own template without issues. For sanity's sake, could you try replacing the Display Names of the fields with the Reference Names? I recommend that anyway, as it is much harder to break with customization. https://msdn.microsoft.com/en-us/library/ms194971.aspx In the mean time I'll try a repro. So you have your latest "SUM" rule for me?

**Comment by holcak** [comment] 2015-05-15 14:26
´´´
  <AggregatorItem name="Test" operationType="Numeric" operation="Sum" linkType="Self" workItemType="Task">
    <TargetField name="Remaining Work"/>  
    <SourceField name="Original Estimate"/>
    <SourceField name="Completed Work"/>
  </AggregatorItem>
´´´

**Comment by holcak** [comment] 2015-05-15 14:27
```
      <FIELD name="Remaining Work" refname="Microsoft.VSTS.Scheduling.RemainingWork" type="Double" reportable="measure" formula="sum">
        <HELPTEXT>An estimate of the number of units of work remaining to complete this task</HELPTEXT>
      </FIELD>
      <FIELD name="Original Estimate" refname="Microsoft.VSTS.Scheduling.OriginalEstimate" type="Double" reportable="measure" formula="sum">
        <HELPTEXT>Initial value for Remaining Work - set once, when work begins</HELPTEXT>
      </FIELD>
      <FIELD name="Completed Work" refname="Microsoft.VSTS.Scheduling.CompletedWork" type="Double" reportable="measure" formula="sum">
        <HELPTEXT>The number of units of work that have been spent on this task</HELPTEXT>
      </FIELD>
```

**Comment by holcak** [comment] 2015-05-15 14:34
test with reference names = the result is the same, aka "0"

**Comment by holcak** [comment] 2015-05-15 14:37
on monday i try this on TFS server 2013 with installed Update 4. Maybe it helps...

**Comment by jessehouwing** [comment] 2015-05-15 14:46
I could reproduce your issue locally (was caused by a subtle Generic Type optimization in the code. Made the generics explicit to prevent this from happening in the future. Please update to the latest bits in https://github.com/tfsaggregator/tfsaggregator/commit/75b5a77a652e13e10717f1433c09f0bfe445706f.

**Closed by jessehouwing** 2015-05-15 14:46 UTC

**Comment by holcak** [comment] 2015-05-18 07:19
thanks
